# services:
#   - type: web
#     name: fullstack-app
#     env: python
#     buildCommand: "./start.sh"
#     startCommand: "python backend/app.py"
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.9
services:
  - type: web
    name: insta-bot-app
    env: python
    plan: free
    buildCommand: "./start.sh"
    startCommand: "./start.sh"
    branch: main
    runtime: python
