services:
  - type: web
    name: fullstack-app
    env: python
    root: src
    buildCommand: "./start.sh"
    startCommand: "python backend/app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
